% m3makefile for metaprogram GenTok of Flint Hills Modula-3.

import("libm3")

include_dir("../../../sharedsrc/intsetssrc") 
include_dir("../../../sharedsrc/layoutsrc") 
include_dir("../../../sharedsrc/vararraysrc")
include_dir("../../../sharedsrc/globalsrc")
include_dir("../../../sharedsrc/lexsrc")
%include_dir("../../../compiler/src/shared")

module("../../fsm/src/FM3BuildLexMachine")
%module("../../sharedsrc/miscsrc/FM3Base")

implementation ("GenTok")
Program("gentok")
