
%(* -----------------------------------------------------------------------1- *)
%(* This file is part of the FM3 Modula-3 compiler.                           *)
%(* Copyright 2023        Rodney M. Bates.                                    *)
%(* rodney.m.bates@acm.org                                                    *)
%(* Licensed under the MIT License.                                           *)
%(* -----------------------------------------------------------------------2- *)

module("../instantiations/FM3OpenArray_Char") 
module("../instantiations/FM3OpenArray_WideChar") 
module("../instantiations/FM3Atom_OAChars") 
module("../instantiations/FM3Atom_OAWideChars") 
module("../instantiations/FM3Dict_OAChars_Int") 

